(cl:defpackage mav_msgs-msg
  (:use )
  (:export
   "<ACTUATORS>"
   "ACTUATORS"
   "<ATTITUDETHRUST>"
   "ATTITUDETHRUST"
   "<DRONESTATE>"
   "DRONESTATE"
   "<FILTEREDSENSORDATA>"
   "FILTEREDSENSORDATA"
   "<GPSWAYPOINT>"
   "GPSWAYPOINT"
   "<RATETHRUST>"
   "RATETHRUST"
   "<ROLLPITCHYAWRATETHRUST>"
   "ROLLPITCHYAWRATETHRUST"
   "<ROLLPITCHYAWRATETHRUSTCRAZYFLIE>"
   "ROLLPITCHYAWRATETHRUSTCRAZYFLIE"
   "<STATUS>"
   "STATUS"
   "<TORQUETHRUST>"
   "TORQUETHRUST"
  ))

