// Generated by gencpp from file rotors_comm/Octomap.msg
// DO NOT EDIT!


#ifndef ROTORS_COMM_MESSAGE_OCTOMAP_H
#define ROTORS_COMM_MESSAGE_OCTOMAP_H

#include <ros/service_traits.h>


#include <rotors_comm/OctomapRequest.h>
#include <rotors_comm/OctomapResponse.h>


namespace rotors_comm
{

struct Octomap
{

typedef OctomapRequest Request;
typedef OctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Octomap
} // namespace rotors_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rotors_comm::Octomap > {
  static const char* value()
  {
    return "a0b5f40a1676bf2554580b1ee723114a";
  }

  static const char* value(const ::rotors_comm::Octomap&) { return value(); }
};

template<>
struct DataType< ::rotors_comm::Octomap > {
  static const char* value()
  {
    return "rotors_comm/Octomap";
  }

  static const char* value(const ::rotors_comm::Octomap&) { return value(); }
};


// service_traits::MD5Sum< ::rotors_comm::OctomapRequest> should match
// service_traits::MD5Sum< ::rotors_comm::Octomap >
template<>
struct MD5Sum< ::rotors_comm::OctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rotors_comm::Octomap >::value();
  }
  static const char* value(const ::rotors_comm::OctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rotors_comm::OctomapRequest> should match
// service_traits::DataType< ::rotors_comm::Octomap >
template<>
struct DataType< ::rotors_comm::OctomapRequest>
{
  static const char* value()
  {
    return DataType< ::rotors_comm::Octomap >::value();
  }
  static const char* value(const ::rotors_comm::OctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rotors_comm::OctomapResponse> should match
// service_traits::MD5Sum< ::rotors_comm::Octomap >
template<>
struct MD5Sum< ::rotors_comm::OctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rotors_comm::Octomap >::value();
  }
  static const char* value(const ::rotors_comm::OctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rotors_comm::OctomapResponse> should match
// service_traits::DataType< ::rotors_comm::Octomap >
template<>
struct DataType< ::rotors_comm::OctomapResponse>
{
  static const char* value()
  {
    return DataType< ::rotors_comm::Octomap >::value();
  }
  static const char* value(const ::rotors_comm::OctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROTORS_COMM_MESSAGE_OCTOMAP_H
