// Generated by gencpp from file rotors_comm/RecordRosbag.msg
// DO NOT EDIT!


#ifndef ROTORS_COMM_MESSAGE_RECORDROSBAG_H
#define ROTORS_COMM_MESSAGE_RECORDROSBAG_H

#include <ros/service_traits.h>


#include <rotors_comm/RecordRosbagRequest.h>
#include <rotors_comm/RecordRosbagResponse.h>


namespace rotors_comm
{

struct RecordRosbag
{

typedef RecordRosbagRequest Request;
typedef RecordRosbagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecordRosbag
} // namespace rotors_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rotors_comm::RecordRosbag > {
  static const char* value()
  {
    return "5504376d5b4669d33bfb29107c817d83";
  }

  static const char* value(const ::rotors_comm::RecordRosbag&) { return value(); }
};

template<>
struct DataType< ::rotors_comm::RecordRosbag > {
  static const char* value()
  {
    return "rotors_comm/RecordRosbag";
  }

  static const char* value(const ::rotors_comm::RecordRosbag&) { return value(); }
};


// service_traits::MD5Sum< ::rotors_comm::RecordRosbagRequest> should match
// service_traits::MD5Sum< ::rotors_comm::RecordRosbag >
template<>
struct MD5Sum< ::rotors_comm::RecordRosbagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rotors_comm::RecordRosbag >::value();
  }
  static const char* value(const ::rotors_comm::RecordRosbagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rotors_comm::RecordRosbagRequest> should match
// service_traits::DataType< ::rotors_comm::RecordRosbag >
template<>
struct DataType< ::rotors_comm::RecordRosbagRequest>
{
  static const char* value()
  {
    return DataType< ::rotors_comm::RecordRosbag >::value();
  }
  static const char* value(const ::rotors_comm::RecordRosbagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rotors_comm::RecordRosbagResponse> should match
// service_traits::MD5Sum< ::rotors_comm::RecordRosbag >
template<>
struct MD5Sum< ::rotors_comm::RecordRosbagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rotors_comm::RecordRosbag >::value();
  }
  static const char* value(const ::rotors_comm::RecordRosbagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rotors_comm::RecordRosbagResponse> should match
// service_traits::DataType< ::rotors_comm::RecordRosbag >
template<>
struct DataType< ::rotors_comm::RecordRosbagResponse>
{
  static const char* value()
  {
    return DataType< ::rotors_comm::RecordRosbag >::value();
  }
  static const char* value(const ::rotors_comm::RecordRosbagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROTORS_COMM_MESSAGE_RECORDROSBAG_H
