// Generated by gencpp from file mav_state_machine_msgs/StartStopTask.msg
// DO NOT EDIT!


#ifndef MAV_STATE_MACHINE_MSGS_MESSAGE_STARTSTOPTASK_H
#define MAV_STATE_MACHINE_MSGS_MESSAGE_STARTSTOPTASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mav_state_machine_msgs
{
template <class ContainerAllocator>
struct StartStopTask_
{
  typedef StartStopTask_<ContainerAllocator> Type;

  StartStopTask_()
    : header()
    , task_name()
    , start(false)  {
    }
  StartStopTask_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_name(_alloc)
    , start(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_name_type;
  _task_name_type task_name;

   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopTask_

typedef ::mav_state_machine_msgs::StartStopTask_<std::allocator<void> > StartStopTask;

typedef boost::shared_ptr< ::mav_state_machine_msgs::StartStopTask > StartStopTaskPtr;
typedef boost::shared_ptr< ::mav_state_machine_msgs::StartStopTask const> StartStopTaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator1> & lhs, const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.task_name == rhs.task_name &&
    lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator1> & lhs, const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_state_machine_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10cd1c89cea1d199a1d9752c42bc712c";
  }

  static const char* value(const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10cd1c89cea1d199ULL;
  static const uint64_t static_value2 = 0xa1d9752c42bc712cULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_state_machine_msgs/StartStopTask";
  }

  static const char* value(const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string task_name\n"
"bool start\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_name);
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopTask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_state_machine_msgs::StartStopTask_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_name);
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_STATE_MACHINE_MSGS_MESSAGE_STARTSTOPTASK_H
