(cl:defpackage mav_planning_msgs-msg
  (:use )
  (:export
   "<POINT2D>"
   "POINT2D"
   "<POINTCLOUDWITHPOSE>"
   "POINTCLOUDWITHPOSE"
   "<POLYGON2D>"
   "POLYGON2D"
   "<POLYGONWITHHOLES>"
   "POLYGONWITHHOLES"
   "<POLYGONWITHHOLESSTAMPED>"
   "POLYGONWITHHOLESSTAMPED"
   "<POLYNOMIALSEGMENT>"
   "POLYNOMIALSEGMENT"
   "<POLYNOMIALSEGMENT4D>"
   "POLYNOMIALSEGMENT4D"
   "<POLYNOMIALTRAJECTORY>"
   "POLYNOMIALTRAJECTORY"
   "<POLYNOMIALTRAJECTORY4D>"
   "POLYNOMIALTRAJECTORY4D"
  ))

