// Generated by gencpp from file burka_pkg/ChangeFormationRequest.msg
// DO NOT EDIT!


#ifndef BURKA_PKG_MESSAGE_CHANGEFORMATIONREQUEST_H
#define BURKA_PKG_MESSAGE_CHANGEFORMATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace burka_pkg
{
template <class ContainerAllocator>
struct ChangeFormationRequest_
{
  typedef ChangeFormationRequest_<ContainerAllocator> Type;

  ChangeFormationRequest_()
    : id(0)  {
    }
  ChangeFormationRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeFormationRequest_

typedef ::burka_pkg::ChangeFormationRequest_<std::allocator<void> > ChangeFormationRequest;

typedef boost::shared_ptr< ::burka_pkg::ChangeFormationRequest > ChangeFormationRequestPtr;
typedef boost::shared_ptr< ::burka_pkg::ChangeFormationRequest const> ChangeFormationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator1> & lhs, const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator1> & lhs, const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace burka_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef7df1d34137d3879d089ad803388efa";
  }

  static const char* value(const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef7df1d34137d387ULL;
  static const uint64_t static_value2 = 0x9d089ad803388efaULL;
};

template<class ContainerAllocator>
struct DataType< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "burka_pkg/ChangeFormationRequest";
  }

  static const char* value(const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
;
  }

  static const char* value(const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeFormationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::burka_pkg::ChangeFormationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::burka_pkg::ChangeFormationRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BURKA_PKG_MESSAGE_CHANGEFORMATIONREQUEST_H
