// Generated by gencpp from file burka_pkg/ChangeFormationResponse.msg
// DO NOT EDIT!


#ifndef BURKA_PKG_MESSAGE_CHANGEFORMATIONRESPONSE_H
#define BURKA_PKG_MESSAGE_CHANGEFORMATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace burka_pkg
{
template <class ContainerAllocator>
struct ChangeFormationResponse_
{
  typedef ChangeFormationResponse_<ContainerAllocator> Type;

  ChangeFormationResponse_()
    : res(0)  {
    }
  ChangeFormationResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int64_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeFormationResponse_

typedef ::burka_pkg::ChangeFormationResponse_<std::allocator<void> > ChangeFormationResponse;

typedef boost::shared_ptr< ::burka_pkg::ChangeFormationResponse > ChangeFormationResponsePtr;
typedef boost::shared_ptr< ::burka_pkg::ChangeFormationResponse const> ChangeFormationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator1> & lhs, const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator1> & lhs, const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace burka_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bc8d07e32bae50e58fb4f23232e6b36";
  }

  static const char* value(const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bc8d07e32bae50eULL;
  static const uint64_t static_value2 = 0x58fb4f23232e6b36ULL;
};

template<class ContainerAllocator>
struct DataType< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "burka_pkg/ChangeFormationResponse";
  }

  static const char* value(const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 res\n"
;
  }

  static const char* value(const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeFormationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::burka_pkg::ChangeFormationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::burka_pkg::ChangeFormationResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int64_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BURKA_PKG_MESSAGE_CHANGEFORMATIONRESPONSE_H
