// Generated by gencpp from file burka_pkg/ChangeFormation.msg
// DO NOT EDIT!


#ifndef BURKA_PKG_MESSAGE_CHANGEFORMATION_H
#define BURKA_PKG_MESSAGE_CHANGEFORMATION_H

#include <ros/service_traits.h>


#include <burka_pkg/ChangeFormationRequest.h>
#include <burka_pkg/ChangeFormationResponse.h>


namespace burka_pkg
{

struct ChangeFormation
{

typedef ChangeFormationRequest Request;
typedef ChangeFormationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeFormation
} // namespace burka_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::burka_pkg::ChangeFormation > {
  static const char* value()
  {
    return "c580c6feba3d09b058407057f8a3cef6";
  }

  static const char* value(const ::burka_pkg::ChangeFormation&) { return value(); }
};

template<>
struct DataType< ::burka_pkg::ChangeFormation > {
  static const char* value()
  {
    return "burka_pkg/ChangeFormation";
  }

  static const char* value(const ::burka_pkg::ChangeFormation&) { return value(); }
};


// service_traits::MD5Sum< ::burka_pkg::ChangeFormationRequest> should match
// service_traits::MD5Sum< ::burka_pkg::ChangeFormation >
template<>
struct MD5Sum< ::burka_pkg::ChangeFormationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::burka_pkg::ChangeFormation >::value();
  }
  static const char* value(const ::burka_pkg::ChangeFormationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::burka_pkg::ChangeFormationRequest> should match
// service_traits::DataType< ::burka_pkg::ChangeFormation >
template<>
struct DataType< ::burka_pkg::ChangeFormationRequest>
{
  static const char* value()
  {
    return DataType< ::burka_pkg::ChangeFormation >::value();
  }
  static const char* value(const ::burka_pkg::ChangeFormationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::burka_pkg::ChangeFormationResponse> should match
// service_traits::MD5Sum< ::burka_pkg::ChangeFormation >
template<>
struct MD5Sum< ::burka_pkg::ChangeFormationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::burka_pkg::ChangeFormation >::value();
  }
  static const char* value(const ::burka_pkg::ChangeFormationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::burka_pkg::ChangeFormationResponse> should match
// service_traits::DataType< ::burka_pkg::ChangeFormation >
template<>
struct DataType< ::burka_pkg::ChangeFormationResponse>
{
  static const char* value()
  {
    return DataType< ::burka_pkg::ChangeFormation >::value();
  }
  static const char* value(const ::burka_pkg::ChangeFormationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BURKA_PKG_MESSAGE_CHANGEFORMATION_H
