// Generated by gencpp from file burka_pkg/FormationMatrix.msg
// DO NOT EDIT!


#ifndef BURKA_PKG_MESSAGE_FORMATIONMATRIX_H
#define BURKA_PKG_MESSAGE_FORMATIONMATRIX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace burka_pkg
{
template <class ContainerAllocator>
struct FormationMatrix_
{
  typedef FormationMatrix_<ContainerAllocator> Type;

  FormationMatrix_()
    : data()  {
    }
  FormationMatrix_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::burka_pkg::FormationMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::burka_pkg::FormationMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct FormationMatrix_

typedef ::burka_pkg::FormationMatrix_<std::allocator<void> > FormationMatrix;

typedef boost::shared_ptr< ::burka_pkg::FormationMatrix > FormationMatrixPtr;
typedef boost::shared_ptr< ::burka_pkg::FormationMatrix const> FormationMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::burka_pkg::FormationMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::burka_pkg::FormationMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::burka_pkg::FormationMatrix_<ContainerAllocator1> & lhs, const ::burka_pkg::FormationMatrix_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::burka_pkg::FormationMatrix_<ContainerAllocator1> & lhs, const ::burka_pkg::FormationMatrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace burka_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burka_pkg::FormationMatrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burka_pkg::FormationMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burka_pkg::FormationMatrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::burka_pkg::FormationMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "burka_pkg/FormationMatrix";
  }

  static const char* value(const ::burka_pkg::FormationMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::burka_pkg::FormationMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FormationMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::burka_pkg::FormationMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::burka_pkg::FormationMatrix_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BURKA_PKG_MESSAGE_FORMATIONMATRIX_H
